-- Create menu_items table
create table public.menu_items (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  description text,
  price numeric not null,
  image_url text,
  category text default 'Meals',
  is_available boolean default true
);

-- Create orders table
create table public.orders (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_email text, -- For simple auth or guest checkout
  user_id uuid references auth.users, -- Optional link to auth
  status text default 'pending', -- pending, preparing, ready, completed, cancelled
  total_amount numeric not null,
  payment_method text default 'cash',
  payment_status text default 'unpaid',
  notes text
);

-- Create order_items table
create table public.order_items (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  order_id bigint references public.orders on delete cascade not null,
  menu_item_id bigint references public.menu_items not null,
  quantity integer default 1,
  price_at_time numeric not null
);

-- Enable Row Level Security (RLS)
alter table public.menu_items enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

-- Policies
-- Menu Items: Everyone can read, only admins can insert/update (simplified for now: everyone read)
create policy "Enable read access for all users" on public.menu_items for select using (true);

-- Orders: Allow public insert and read (for guest checkout)
create policy "Enable insert for everyone" on public.orders for insert with check (true);
create policy "Enable read for everyone" on public.orders for select using (true);

-- Order Items: Allow public insert and read
create policy "Enable insert for everyone" on public.order_items for insert with check (true);
create policy "Enable read for everyone" on public.order_items for select using (true);

-- Insert initial data
insert into public.menu_items (name, description, price, category, image_url)
values 
('Fried Chicken Meal', '2 pieces of crispy fried chicken with rice', 150.00, 'Meals', 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=800&q=80'),
('Spicy Fried Chicken', '2 pieces of spicy crispy chicken with rice', 160.00, 'Meals', 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=800&q=80');
